---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: sfcn-gitops-cust1-stack1
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/GaneshManal/sfcn-test-cust-config.git
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: sfcn
  namespace: flux-system
spec:
  interval: 5m0s # detect drift and undo kubectl edits every 5 min
  #wait: true # wait for all applied resources to become ready
  timeout: 10m0s # give up waiting after three minutes
  retryInterval: 2m0s # retry every two minutes on apply or waiting failures
  prune: true # remove stale resources from cluster
  force: true # recreate resources on immutable fields changes
  #targetNamespace: apps # set the namespace for all resources
  sourceRef:
    kind: GitRepository
    name: sfcn-gitops-cust1-stack1
    namespace: flux-system
  path: "./clusters/cust1-stack1/sfcn-system"
