apiVersion: v1
kind: ConfigMap
metadata:
  name: sfcn-helm-values
  namespace: sfcn-system
data:
  values.yaml: |-
    # For dev, values can be overwritten using sfcn-helm-dev-values Secret
    global:
      forceUpgradeDeployments: [sfcn-system/sfcn-vpnredirector-enforcer,sfcn-system/sfcn-cag-enforcer]
      acceptEULA: "yes"
      platform: "eks"
      storageType: local
      imageCredentials:
        registry: 709825985650.dkr.ecr.us-east-1.amazonaws.com
        artifactoryRepo: cisco/sfcn/prod
        username: ""
        password: ""
      dataPlaneNamespace: sfcn-system
      sfcDataPlaneNodeGroup: epworkers
      eks:
        clusterName: cust1-gam-us-west-1
    tags:
      controlPlane: true
      dataPlane: true
    dataPlane:
      serviceRoles: [vpnredirector,cnfwentry,cntdmid,sfcexit]
      configurationTier: vCPU8Mem16Gi
      redis:
        host: None
        port: 6379
      hpa:
        enable: true
      publicIPs: [outside]
    snmpExporter:
      serviceRoles: [vpnredirector,cnfwentry]
    scaledown:
      enable: true
    cagAdmin:
      redis:
        port: 6379
        host: None
    apiServer:
      serviceRoles: [cnfwentry]
      redis:
        host: None
        port: 6379

