apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sfcn
  namespace: sfcn-system
spec:
  chart:
    spec:
      chart: sfcn-bundle
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: sfcn-helm-repo
        namespace: sfcn-system
      version: v0.0.0-145
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
    - name: prometheus-adapter
      namespace: kube-system
    - name: autoscaler
      namespace: kube-system
  interval: 1m0s
  timeout: 10m0s
  valuesFrom:
    - kind: ConfigMap
      name: sfcn-helm-values
    - kind: Secret
      name: sfcn-helm-reg-override
      optional: true
